wiki/encyclopedia/urls.py
from django.urls import path

from . import views
app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.title, name="title"),
    path("wiki/<str:title>/edit_page", views.edit_page, name="edit_page"),
    path("search", views.search, name="search"),
    path("new_page", views.new_page, name="new_page"),
    path("random", views.random_page, name="random_page") 
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django import forms
import markdown2
from markdown2 import Markdown
import random
from . import util

class PageForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    content = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control", "rows":"3", "columns":"6"}))

class EditForm(forms.Form):
    edit_content = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control", "rows":"3", "columns":"6"}))  

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def title(request, title):
    if util.get_entry(title) == None:
        return render(request, "encyclopedia/error.html",{
            "search": True, 
        })
    else:
        return render(request, "encyclopedia/title.html",{
            "content": Markdown().convert(util.get_entry(title)), "title":title
        })
    
    
def search(request):
    if request.method == "GET":
        search_entry = request.GET.get("q").upper()
        if util.get_entry(search_entry) is not None: #able to find result
            return HttpResponseRedirect(reverse("encyclopedia:title", kwargs={"title":search_entry}))
        else:
            # there is no result
            # find the substring!
            match = [] #this list stores the match results
            for entry in util.list_entries():
                if search_entry.lower() in entry.lower():
                    #return to result page
                    match.append(entry)
            
            if len(match) != 0:
                return render(request, "encyclopedia/result.html", {
                    "results": match 
                })
            else:
                return render(request, "encyclopedia/error.html",{
                    "search": True,
                })


def new_page(request):
    if request.method == "POST":
        form = PageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            if util.get_entry(title) == None:
                content = form.cleaned_data["content"]
                util.save_entry(title, content)
                return HttpResponseRedirect(reverse("encyclopedia:title", kwargs={'title': title}))

            else:
                render(request, "encyclopedia/error.html", {
                    "search": False,
                })
    return render(request, "encyclopedia/new_page.html",{
        "form": PageForm()
    })

def edit_page(request, title):

    if request.method == "POST":
        form = EditForm(request.POST)

        if form.is_valid():
            content = form.cleaned_data["edit_content"]
            util.save_entry(title, content)
            return HttpResponseRedirect(reverse("encyclopedia:title", kwargs={'title': title}))
    else:
        form = EditForm()
        form.fields["edit_content"].initial = util.get_entry(title)
        return render(request, "encyclopedia/edit_page.html",{
            "form": form,
            "title": title
        })
            
def random_page(request):
    all_entries = util.list_entries()
    random_choice = random.choice(all_entries)
    return HttpResponseRedirect(reverse("encyclopedia:title", kwargs={'title': random_choice}))

wiki/encyclopedia/templates/encyclopedia/edit_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Edit page
{% endblock %}

{% block body %}

<form action="{% url 'encyclopedia:edit_page' title %}" method="POST">
    {% csrf_token %}
    {{form}}
    
    <input type="submit">
</form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    {% if search %}
        <h4>Couldn't find what you are looking for!</h4>
    {% else %}
        <h4>Your entry already existed!</h4>
    {% endif %}
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:title' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="GET">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:new_page' %}">Create New Page</a>  
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
New Page
{% endblock %}


{% block body %}

<form action="{% url 'encyclopedia:new_page' %}" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/result.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search Result
{% endblock %}


{% block body %}
    {% for result in results %}
        <li><a href="{% url 'encyclopedia:title' result %}">{{result}}</a></li>
    {% endfor %}

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/title.html
{% extends "encyclopedia/layout.html" %} 

{% block title %} 

{{title}}

{% endblock %} 

{% block body %}

    {{ content|safe }}
    <a href="{% url 'encyclopedia:edit_page' title %}">Edit</a>
{% endblock %}